package com.myspace.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class sampleobject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public sampleobject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public sampleobject(java.lang.String name) {
		this.name = name;
	}

}